version: '3.8'

services:
  mongo:
    image: mongo:5.0
    container_name: blog_mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: Omani2025
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - mongodb_data:/data/db
    ports:
      - "27018:27017"  # Changed from 27017:27017
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh -u root -p Omani2025 --quiet
      interval: 30s
      timeout: 10s
      retries: 3

  server:
    build: ./server
    container_name: blog_server
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
      - JWT_SECRET=your_jwt_secret_here
      - MONGO_URI=mongodb://blog_user:blog_password123@mongo:27017/blog?authSource=blog
    depends_on:
      mongo:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  client:
    build: ./client
    container_name: blog_client
    ports:
      - "3000:3000"
    depends_on:
      - server

volumes:
  mongodb_data:
